#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (set = 0, binding = 0, rgba8) uniform mediump image2D inputImage;

layout( push_constant ) uniform constants {
    float gamma;
    float exposure;
} push;

void main() {   
    vec4 color = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y));
    // exposure tone mapping
    vec3 corrected = vec3(1.0) - exp(-color.rgb * push.exposure);
    // gamma correction
    color = vec4(pow(corrected, vec3(1 / push.gamma)), color.a);
    imageStore(inputImage, ivec2(gl_GlobalInvocationID.xy), color);
}